export const CLEAN_DATA_CONFIRMATION = "CLEAN_PROSPERA_DATA";

export const DEFAULT_PRESERVED_ADMIN_EMAILS = [
  "admin@prosperasub.local",
  "frorex.studio@gmail.com"
];

export type ResetClassification = {
  systemData: string[];
  defaultSeedData: string[];
  userGeneratedData: string[];
  auditData: string[];
};

export type ResetValidationOptions = {
  execute: boolean;
  confirmation?: string;
  allowProduction: boolean;
  preservedAdminEmails: string[];
  isProduction?: boolean;
};

export type ResetSqlOptions = {
  preservedAdminEmails: string[];
  deleteAuditLogs: boolean;
};

const DEFAULT_CLEANING_STUDIO_ID = "00000000-0000-4000-8000-000000000201";
const DEFAULT_CLEANING_TWO_BEDROOM_ID = "00000000-0000-4000-8000-000000000202";

const resettableTablesInFkOrder = [
  "cleaning_completion_reports",
  "cleaning_bookings",
  "cleaning_recurring_schedules",
  "cleaning_checklist_templates",
  "cleaning_custom_plans",
  "cleaning_plan_client_assignments",
  "cleaning_clients",
  "cleaning_subscriptions",
  "cleaning_available_slots",
  "payment_checkout_sessions",
  "payments",
  "tournament_applications"
];

const auditTables = [
  "admin_audit_logs",
  "admin_payment_notifications",
  "login_history",
  "lightning_auth_sessions"
];

export function classifyResetData(): ResetClassification {
  return {
    systemData: [
      "supabase_migrations",
      "auth.users",
      "public.users:preserved_admins",
      "public.user_roles:preserved_admin_roles",
      "enums",
      "functions",
      "rls_policies",
      "foreign_keys",
      "migrations"
    ],
    defaultSeedData: [
      "global_settings",
      "cleaning_packages"
    ],
    userGeneratedData: [
      ...resettableTablesInFkOrder,
      "user_profiles:non_preserved",
      "user_sessions:non_preserved",
      "user_roles:non_preserved",
      "users:non_preserved"
    ],
    auditData: auditTables
  };
}

export function validateResetOptions(options: ResetValidationOptions) {
  if (options.preservedAdminEmails.length < 1) {
    throw new Error("At least one preserved admin email is required.");
  }

  if (options.execute && options.confirmation !== CLEAN_DATA_CONFIRMATION) {
    throw new Error(`Execute mode requires --confirm ${CLEAN_DATA_CONFIRMATION}.`);
  }

  if (options.execute && options.isProduction && !options.allowProduction) {
    throw new Error("Production resets require --allow-production.");
  }
}

export function buildSafeDataResetSql(options: ResetSqlOptions) {
  const preservedEmails = normalizeEmails(options.preservedAdminEmails);
  validateResetOptions({
    execute: false,
    confirmation: undefined,
    allowProduction: false,
    preservedAdminEmails: preservedEmails
  });

  const resetDeletes = [
    ...resettableTablesInFkOrder.map((tableName) => dynamicDelete(tableName)),
    dynamicDelete("user_sessions", "user_id::text NOT IN (SELECT id FROM _prospera_preserved_admins)"),
    dynamicDelete("user_profiles", "user_id::text NOT IN (SELECT id FROM _prospera_preserved_admins)"),
    dynamicDelete("user_roles", "user_id::text NOT IN (SELECT id FROM _prospera_preserved_admins)"),
    dynamicDelete("users", "id::text NOT IN (SELECT id FROM _prospera_preserved_admins)")
  ];

  const auditDeletes = options.deleteAuditLogs ? auditTables.map((tableName) => dynamicDelete(tableName)) : [];

  return [
    "-- Prospera Sub safe data reset",
    "-- Generated by backend/src/admin/data-reset-plan.ts",
    "BEGIN;",
    "SET LOCAL lock_timeout = '10s';",
    "SET LOCAL statement_timeout = '5min';",
    "SELECT pg_advisory_xact_lock(hashtext('prospera_safe_data_reset'));",
    buildPreservedAdminsSql(preservedEmails),
    buildDoBlock([...resetDeletes, ...auditDeletes]),
    buildReseedSql(),
    buildFinalAdminCheckSql(),
    "COMMIT;",
    ""
  ].join("\n\n");
}

function normalizeEmails(emails: string[]) {
  return [...new Set(emails.map((email) => email.trim().toLowerCase()).filter(Boolean))];
}

function buildPreservedAdminsSql(preservedEmails: string[]) {
  const emailArray = preservedEmails.map(quoteSqlLiteral).join(", ");

  return `CREATE TEMP TABLE _prospera_preserved_admins (id text PRIMARY KEY);

DO $$
DECLARE
  v_preserved_emails text[] := ARRAY[${emailArray}]::text[];
  v_admin_count integer;
BEGIN
  IF to_regclass('public.users') IS NULL THEN
    RAISE EXCEPTION 'Safe reset aborted: public.users table is missing';
  END IF;

  IF to_regclass('public.user_roles') IS NULL THEN
    RAISE EXCEPTION 'Safe reset aborted: public.user_roles table is missing';
  END IF;

  INSERT INTO _prospera_preserved_admins (id)
  SELECT u.id::text
  FROM public.users u
  WHERE lower(coalesce(u.email, '')) = ANY(v_preserved_emails)
    AND EXISTS (
      SELECT 1
      FROM public.user_roles ur
      WHERE ur.user_id::text = u.id::text
        AND lower(ur.role::text) = 'super_admin'
    );

  SELECT count(*) INTO v_admin_count FROM _prospera_preserved_admins;

  IF v_admin_count < 1 THEN
    RAISE EXCEPTION 'Safe reset aborted: no preserved super admin account found';
  END IF;
END $$;`;
}

function buildDoBlock(statements: string[]) {
  return `DO $$
BEGIN
${statements.map((statement) => indent(statement, 2)).join("\n")}
END $$;`;
}

function buildReseedSql() {
  return buildDoBlock([
    dynamicStatementIfTableColumns(
      "global_settings",
      ["min_subscription_weeks", "max_subscription_weeks", "platform_fee_percent"],
      `INSERT INTO public.global_settings (
  min_subscription_weeks,
  max_subscription_weeks,
  platform_fee_percent
)
SELECT 1, 4, 0
WHERE NOT EXISTS (SELECT 1 FROM public.global_settings)`
    ),
    dynamicStatementIfTableColumns(
      "cleaning_packages",
      ["id", "name", "cleanings_per_month", "price_per_cleaning_cents", "frequency_unit", "frequency_count", "pricing_mode", "monthly_price_cents", "is_active", "updated_at"],
      `INSERT INTO public.cleaning_packages (
  id,
  name,
  cleanings_per_month,
  price_per_cleaning_cents,
  frequency_unit,
  frequency_count,
  pricing_mode,
  monthly_price_cents,
  is_active
)
VALUES
  ('${DEFAULT_CLEANING_STUDIO_ID}', '1 Bedroom & Studio', 4, 1975, 'month', 4, 'price_per_cleaning', 7900, true),
  ('${DEFAULT_CLEANING_TWO_BEDROOM_ID}', '2 Bedroom', 4, 2475, 'month', 4, 'price_per_cleaning', 9900, true)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    cleanings_per_month = EXCLUDED.cleanings_per_month,
    price_per_cleaning_cents = EXCLUDED.price_per_cleaning_cents,
    frequency_unit = EXCLUDED.frequency_unit,
    frequency_count = EXCLUDED.frequency_count,
    pricing_mode = EXCLUDED.pricing_mode,
    monthly_price_cents = EXCLUDED.monthly_price_cents,
    is_active = true,
    updated_at = now()`
    )
  ]);
}

function buildFinalAdminCheckSql() {
  return `DO $$
DECLARE
  v_admin_count integer;
BEGIN
  SELECT count(*) INTO v_admin_count
  FROM public.users u
  JOIN public.user_roles ur ON ur.user_id::text = u.id::text
  WHERE u.id::text IN (SELECT id FROM _prospera_preserved_admins)
    AND lower(ur.role::text) = 'super_admin';

  IF v_admin_count < 1 THEN
    RAISE EXCEPTION 'Safe reset aborted: preserved super admin was lost during cleanup';
  END IF;
END $$;`;
}

function dynamicDelete(tableName: string, whereClause = "true") {
  assertSafeIdentifier(tableName);
  return dynamicStatementIfTable(tableName, `DELETE FROM public.${tableName} WHERE ${whereClause}`);
}

function dynamicStatementIfTable(tableName: string, sql: string) {
  assertSafeIdentifier(tableName);
  return `IF to_regclass('public.${tableName}') IS NOT NULL THEN
  EXECUTE ${dollarQuote(sql)};
END IF;`;
}

function dynamicStatementIfTableColumns(tableName: string, columns: string[], sql: string) {
  assertSafeIdentifier(tableName);
  columns.forEach(assertSafeIdentifier);
  const columnList = columns.map(quoteSqlLiteral).join(", ");

  return `IF to_regclass('public.${tableName}') IS NOT NULL
  AND (
    SELECT count(*)
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = ${quoteSqlLiteral(tableName)}
      AND column_name IN (${columnList})
  ) = ${columns.length} THEN
  EXECUTE ${dollarQuote(sql)};
END IF;`;
}

function dollarQuote(value: string) {
  return `$prospera_sql$${value}$prospera_sql$`;
}

function quoteSqlLiteral(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function assertSafeIdentifier(value: string) {
  if (!/^[a-z][a-z0-9_]*$/.test(value)) {
    throw new Error(`Unsafe SQL identifier: ${value}`);
  }
}

function indent(value: string, spaces: number) {
  const prefix = " ".repeat(spaces);
  return value
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n");
}
